# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c09bf416503a1f4ab586a21ee807a70eb4f7291e96cebfe6a7117b8e10f768cb20c9f1e6009d4df30fc41818ab7f8cf7228cbffc8ed261c007b2f716bafe83a9

test:
  secret_key_base: 7e84d17fb81b993bb6c1299835e5e712082a0a78b67aad675ca2ce62adc40bba4f995791c99cfaf2435ed7e13d931be1e68bd1a0318a81c0d4c05384f7941670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
